const SET_LISTS = "lists/SET_LISTS";
const ADD_LIST_SUCCESS = "lists/ADD_LIST_SUCCESS";

const DELETE_LIST_SUCCESS = "lists/DELETE_LIST_SUCCESS";

export { SET_LISTS, ADD_LIST_SUCCESS, DELETE_LIST_SUCCESS };
